### ISSUE TITLE
Daily cron job on Travis

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/homebrew-helics#2]
Since this is intended as a brew script for installing Helics on macs we should have a travis cron job that runs occasionally to make sure that works properly.    Most changes are likely to be in HELICS so I think a cron job that tests it daily is probably sufficient.  And I think a single job will likely be sufficient.

**Comment by kdheepak** [comment]
This is partially addressed in eda2d0434234ef7ef5512748cd101c1bcd022db3

See [log](https://travis-ci.org/GMLC-TDC/homebrew-helics/builds/335228204) for successful `brew install helics` on Travis.

**Comment by kdheepak** [comment]
I've added a daily cron job using the Travis web interface. @nightlark let me know if there are any changes required to be made to the `.travis.yml` file. If not we can close this issue.

**Comment by nightlark** [comment]
@kdheepak it should run without any changes to .travis.yml

**Comment by kdheepak** [comment]
Great!
